import { inngest } from "../client";
import { prisma } from "@codeunicorn/database";
import { retrieveContext } from "@codeunicorn/ai";
import { postIssueComment } from "@codeunicorn/github";
import { generateObject } from "ai";
import { google } from "@ai-sdk/google";
import { z } from "zod";

const issueAnalysisSchema = z.object({
  relevantFiles: z
    .array(
      z.object({
        path: z.string().describe("File path relative to repo root"),
        reason: z
          .string()
          .describe("1-2 sentence explanation of why this file is relevant"),
      })
    )
    .describe("Up to 8 files most likely related to this issue"),
  suggestedLabels: z
    .array(z.string())
    .describe(
      "2-4 GitHub label names to apply (e.g. bug, enhancement, ui, auth, performance)"
    ),
  summary: z
    .string()
    .describe(
      "2-3 sentence analysis of what the issue is about and which part of the codebase is likely involved"
    ),
});

export const analyzeIssue = inngest.createFunction(
  { id: "analyze-issue", concurrency: 5 },
  { event: "issue.created" },

  async ({ event, step }) => {
    const {
      owner,
      repo,
      issueNumber,
      issueTitle,
      issueBody,
      issueUrl,
      repositoryId,
      userId,
    } = event.data;

    // Step 1: Retrieve relevant codebase context
    const context = await step.run("retrieve-context", async () => {
      const query = `${issueTitle}\n${issueBody || ""}`;
      return retrieveContext(query, repositoryId, 10);
    });

    // Step 2: Generate analysis with Gemini
    const analysis = await step.run("generate-analysis", async () => {
      const { object } = await generateObject({
        model: google("gemini-2.5-flash"),
        schema: issueAnalysisSchema,
        prompt: `You are an expert code reviewer helping triage a GitHub issue.

Repository: ${owner}/${repo}
Issue #${issueNumber}: ${issueTitle}
Issue Body: ${issueBody || "(no body provided)"}

Relevant codebase context (from vector index):
${context.join("\n\n---\n\n")}

Based on the issue description and codebase context, identify:
1. Which files/modules are most likely relevant to this issue (be specific, reference actual paths from context)
2. Suggested GitHub labels for this issue
3. A brief summary of what the issue is about and which system area is involved`,
      });
      return object;
    });

    // Step 3: Post comment on the GitHub issue
    const commentPosted = await step.run("post-comment", async () => {
      try {
        const account = await prisma.account.findFirst({
          where: { userId, providerId: "github" },
        });
        if (!account?.accessToken) return false;

        const relevantFilesTable =
          analysis.relevantFiles.length > 0
            ? `| File | Why |\n|---|---|\n${analysis.relevantFiles.map((f) => `| \`${f.path}\` | ${f.reason} |`).join("\n")}`
            : "_No specific files identified._";

        const labelsText =
          analysis.suggestedLabels.length > 0
            ? analysis.suggestedLabels.map((l) => `\`${l}\``).join(", ")
            : "_None suggested_";

        const body = `## 🦄 CodeUnicorn Issue Analysis

${analysis.summary}

### Likely Related Files

${relevantFilesTable}

**Suggested labels:** ${labelsText}

---
*Automatically generated by [CodeUnicorn](https://github.com/anjany06/codeUnicorn-monorepo) · AI-powered codebase intelligence*`;

        await postIssueComment(account.accessToken, owner, repo, issueNumber, body);
        return true;
      } catch (error) {
        console.error("Failed to post issue comment:", error);
        return false;
      }
    });

    // Step 4: Save analysis to database
    await step.run("save-analysis", async () => {
      await prisma.issueAnalysis.create({
        data: {
          repositoryId,
          issueNumber,
          issueTitle,
          issueUrl,
          analysis: JSON.stringify(analysis),
          postedComment: commentPosted,
        },
      });
    });

    return {
      success: true,
      issueNumber,
      relevantFiles: analysis.relevantFiles.length,
      commentPosted,
    };
  }
);
